# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

datos = %q{ANDRESITO,IGUAZU
IGUAZU,IGUAZU
LIBERTAD,PARANA
EL DORADO,PARANA
LIBERTADOR,PARANA
SANTA ANA,PARANA
PUERTO MANI,PARANA
POSADAS,PARANA
ITUZAINGO,PARANA
ITA IBATE,PARANA
ITATI,PARANA
PASO DE LA PATRIA,PARANA
CORRIENTES,PARANA
BARRANQUERAS,PARANA
EMPEDRADO,PARANA
BELLA VISTA,PARANA
GOYA,PARANA
RECONQUISTA,PARANA
ESQUINA,PARANA
LA PAZ,PARANA
SANTA ELENA,PARANA
HERNANDARIAS,PARANA
PARANA,PARANA
SANTA FE,PARANA
DIAMANTE,PARANA
VICTORIA,PARANA
SAN LORENZO,PARANA
ROSARIO,PARANA
VILLA CONSTITUCION,PARANA
SAN NICOLAS,PARANA
RAMALLO,PARANA
SAN PEDRO,DELTA PARANA
BARADERO,DELTA PARANA
ZARATE,DELTA PARANA
CAMPANA,DELTA PARANA
ESCOBAR,DELTA PARANA
PARANACITO,URUGUAY
CANAL NUEVO,DELTA PARANA
IBICUY,DELTA PARANA
MARTIN GARCIA,DELTA PARANA
GUAZUCITO,DELTA PARANA
TIGRE,DELTA PARANA
DIQUE LUJAN,DELTA PARANA
CHANA MINI,DELTA PARANA
SAN FERNANDO,DELTA PARANA
SAN ISIDRO,DELTA PARANA
OLIVOS,DELTA PARANA
PILCOMAYO,PARAGUAY
BOUVIER,PARAGUAY
FORMOSA,PARAGUAY
SAN JAVIER,URUGUAY
BARRA CONCEPCION,URUGUAY
GARRUCHOS,URUGUAY
SANTO TOME,URUGUAY
ALVEAR,URUGUAY
LA CRUZ,URUGUAY
YAPEYU,URUGUAY
PASO DE LOS LIBRES,URUGUAY
BONPLAND,URUGUAY
MONTE CASEROS,URUGUAY
MOCORETA,URUGUAY
FEDERACION,URUGUAY
FEDERACION EMBALSE,URUGUAY
SALTO GRANDE ARRIBA,URUGUAY
SALTO GRANDE ABAJO,URUGUAY
CONCORDIA,URUGUAY
COLON,URUGUAY
CONCEPCION DEL URUGUAY,URUGUAY
CAMPICHUELO,URUGUAY
GUALEGUAYCHU,URUGUAY
BOCA GUALEGUAYCHU,URUGUAY
PUERTO RUIZ,URUGUAY
BUENOS AIRES,DE LA PLATA
LA PLATA,DE LA PLATA
BRAGA,DE LA PLATA
SANTA TERESITA,DE LA PLATA
ATALAYA,DE LA PLATA}

datos.split("\n").each do |linea|
  nombre_puerto, nombre_rio = linea.split(",")
  rio = Rio.where(nombre: nombre_rio).first || Rio.create(nombre: nombre_rio)
  puerto = Puerto.where(nombre: nombre_puerto).first || Puerto.create(nombre: nombre_puerto)

  puerto.rio_id = rio.id
  puerto.save
end

Puerto.find(13).update_attributes(altura_alerta: 6.50, altura_evacuacion: 7)
Altura.create(puerto_id: 13, medicion: 7.18, fecha: DateTime.now)